language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -d include_path=vendor/google/appengine-php-sdk/

after_script:
  - php vendor/bin/coveralls -v