language: php

matrix:
    include:
        - php: 5.4
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
        - php: 5.5
        - php: 5.6
        - php: 7.0

before_script:
  - composer self-update
  - composer install ${COMPOSER_FLAGS}

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit 

after_script:
  - php vendor/bin/coveralls -v
